// Generated by CoffeeScript 1.7.1
;(function() {
  var PING_DELAY,
    counter,
    previous,
    rclient1,
    rclient2,
    redis,
    sendPing,
    sendPings

  redis = require('redis-sharelatex')

  rclient1 = redis.createClient({
    cluster: [
      {
        port: '7000',
        host: 'localhost'
      }
    ]
  })

  rclient2 = redis.createClient({
    cluster: [
      {
        port: '7000',
        host: 'localhost'
      }
    ]
  })

  counter = 0

  sendPing = function(cb) {
    if (cb == null) {
      cb = function() {}
    }
    return rclient1.publish('test-pubsub', counter, function(error) {
      if (error != null) {
        console.error('[SENDING ERROR]', error.message)
      }
      if (error == null) {
        counter += 1
      }
      return cb()
    })
  }

  previous = null

  rclient2.subscribe('test-pubsub')

  rclient2.on('message', function(channel, value) {
    value = parseInt(value, 10)
    if (value % 10 === 0) {
      console.log('.')
    }
    if (previous != null && value !== previous + 1) {
      console.error(
        '[RECEIVING ERROR]',
        'Counter not in order. Got ' + value + ', expected ' + (previous + 1)
      )
    }
    return (previous = value)
  })

  PING_DELAY = 100

  ;(sendPings = function() {
    return sendPing(function() {
      return setTimeout(sendPings, PING_DELAY)
    })
  })()
}.call(this))
